name: Pull request labelling
on:
    pull_request:
        branches:
            - "master"

jobs:
    pr_label:
        if: github.repository == 'DemonDaddy22/MD-Editor'
        runs-on: ubuntu-latest
        steps:
            - name: Adding label
              uses: actions/labeler@main
              with:
                  sync-labels: true
                  repo-token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
